version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    container_name: web
    image: wenerikk/api_yamdb:latest
#    build: ../
    command: >
      sh -c "python /app/manage.py makemigrations &&
             python /app/manage.py migrate &&
             python /app/manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 api_yamdb.wsgi:application"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
